### ISSUE TITLE
Filter on both subject and attachments

### ISSUE THREAD

**Issue by jkaberg** [emcniece/ha_imap_attachment#3]
Thanks for this fantastic addition @emcniece ! 

I was wondering if you'd consider implementing:
 - regex matching for
   - (email) subject (only match if subject is x,y)
     - possibly stop after first match?
   - attachments (only fetch file if filename is x,y)
     - possibly stop after first match?

I get a lot of emails from one adress, only of which few of these contains relevant information. Then in the relevant email there are sometimes several files

**Comment by jkaberg** [comment]
Maybe something like:
```
sensor:
  - platform: imap_attachment
    name: Utility Bill Email
    server: imap.gmail.com
    port: 993
    username: user@domain.com
    password: hunter2
    senders:
      noreply@somedomain.com:
        regex_subject: 
        regex_subject_stop_after:
        regex_attachment:
        regex_attachment_stop_after:
```
